name: mangamint
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  bloc: ^5.0.1
  flutter_bloc: ^5.0.1
  google_fonts: ^1.1.0
  equatable: ^1.2.0
  provider: ^4.3.0
  rxdart: ^0.24.1
  ff_navigation_bar: ^0.1.5
  flutter_spinkit: ^4.1.2+1
  shimmer: ^1.1.1
  carousel_slider: ^2.2.1
  flutter_screenutil: ^2.2.0
  cached_network_image: ^2.2.0+1
  photo_view: ^0.10.3
  shared_preferences: ^0.5.8
  path_provider: ^1.6.11
  path: ^1.7.0
  hive: ^1.4.1+1
  hive_flutter: ^0.2.1
  toast: ^0.1.5
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.5.0
  extended_image: ^0.9.0
  dio: ^3.0.10

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.7.5
  hive_generator: ^0.5.1
  build_runner:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/icon.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/aqua.JPG
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
